// Company interface
export interface Company {
  id: number;
  name: string;
  image: string;
  images: string[];
}

// Data
export const companies: Company[] = [
  {
    id: 1,
    name: "Promosyon",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-G.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-S.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-L.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-B.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-TRK.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-T.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-K.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/landscaping.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/real_estate.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/minimalist.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/construction.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/modern_template.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/square.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/gloss.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/standard.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/popular.png",
    ],
  },
  {
    id: 2,
    name: "PromoLine",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://example.com/assets/img/products/promo1.jpg",
      "https://example.com/assets/img/products/promo2.jpg",
      "https://example.com/assets/img/products/promo3.jpg",
      "https://example.com/assets/img/products/promo4.jpg",
      "https://example.com/assets/img/products/promo5.jpg",
      "https://example.com/assets/img/products/promo6.jpg",
      "https://example.com/assets/img/products/promo7.jpg",
      "https://example.com/assets/img/products/promo8.jpg",
      "https://example.com/assets/img/products/promo9.jpg",
      "https://example.com/assets/img/products/promo10.jpg",
      "https://example.com/assets/img/products/promo11.jpg",
      "https://example.com/assets/img/products/promo12.jpg",
      "https://example.com/assets/img/products/promo13.jpg",
      "https://example.com/assets/img/products/promo14.jpg",
      "https://example.com/assets/img/products/promo15.jpg",
      "https://example.com/assets/img/products/promo16.jpg",
    ],
  },
  {
    id: 3,
    name: "Promosyon",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-G.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-S.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-L.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-B.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-TRK.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-T.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-K.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/landscaping.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/real_estate.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/minimalist.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/construction.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/modern_template.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/square.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/gloss.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/standard.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/popular.png",
    ],
  },
  {
    id: 4,
    name: "PromoLine",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://example.com/assets/img/products/promo1.jpg",
      "https://example.com/assets/img/products/promo2.jpg",
      "https://example.com/assets/img/products/promo3.jpg",
      "https://example.com/assets/img/products/promo4.jpg",
      "https://example.com/assets/img/products/promo5.jpg",
      "https://example.com/assets/img/products/promo6.jpg",
      "https://example.com/assets/img/products/promo7.jpg",
      "https://example.com/assets/img/products/promo8.jpg",
      "https://example.com/assets/img/products/promo9.jpg",
      "https://example.com/assets/img/products/promo10.jpg",
      "https://example.com/assets/img/products/promo11.jpg",
      "https://example.com/assets/img/products/promo12.jpg",
      "https://example.com/assets/img/products/promo13.jpg",
      "https://example.com/assets/img/products/promo14.jpg",
      "https://example.com/assets/img/products/promo15.jpg",
      "https://example.com/assets/img/products/promo16.jpg",
    ],
  },
  {
    id: 5,
    name: "Promosyon",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-G.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-S.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-L.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-B.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-TRK.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-T.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-K.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/landscaping.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/real_estate.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/minimalist.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/construction.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/modern_template.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/square.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/gloss.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/standard.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/popular.png",
    ],
  },
  {
    id: 6,
    name: "PromoLine",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://example.com/assets/img/products/promo1.jpg",
      "https://example.com/assets/img/products/promo2.jpg",
      "https://example.com/assets/img/products/promo3.jpg",
      "https://example.com/assets/img/products/promo4.jpg",
      "https://example.com/assets/img/products/promo5.jpg",
      "https://example.com/assets/img/products/promo6.jpg",
      "https://example.com/assets/img/products/promo7.jpg",
      "https://example.com/assets/img/products/promo8.jpg",
      "https://example.com/assets/img/products/promo9.jpg",
      "https://example.com/assets/img/products/promo10.jpg",
      "https://example.com/assets/img/products/promo11.jpg",
      "https://example.com/assets/img/products/promo12.jpg",
      "https://example.com/assets/img/products/promo13.jpg",
      "https://example.com/assets/img/products/promo14.jpg",
      "https://example.com/assets/img/products/promo15.jpg",
      "https://example.com/assets/img/products/promo16.jpg",
    ],
  },
  {
    id: 7,
    name: "Promosyon",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-G.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-S.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-L.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-B.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-TRK.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-T.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-K.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/landscaping.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/real_estate.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/minimalist.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/construction.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/modern_template.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/square.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/gloss.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/standard.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/popular.png",
    ],
  },
  {
    id: 8,
    name: "PromoLine",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://example.com/assets/img/products/promo1.jpg",
      "https://example.com/assets/img/products/promo2.jpg",
      "https://example.com/assets/img/products/promo3.jpg",
      "https://example.com/assets/img/products/promo4.jpg",
      "https://example.com/assets/img/products/promo5.jpg",
      "https://example.com/assets/img/products/promo6.jpg",
      "https://example.com/assets/img/products/promo7.jpg",
      "https://example.com/assets/img/products/promo8.jpg",
      "https://example.com/assets/img/products/promo9.jpg",
      "https://example.com/assets/img/products/promo10.jpg",
      "https://example.com/assets/img/products/promo11.jpg",
      "https://example.com/assets/img/products/promo12.jpg",
      "https://example.com/assets/img/products/promo13.jpg",
      "https://example.com/assets/img/products/promo14.jpg",
      "https://example.com/assets/img/products/promo15.jpg",
      "https://example.com/assets/img/products/promo16.jpg",
    ],
  },
  {
    id: 9,
    name: "Promosyon",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-G.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-S.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-L.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-B.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-TRK.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-T.jpg",
      "https://drpromosyon.com/assets/img/katalog/urunler/Y2025-K.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/landscaping.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/real_estate.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/minimalist.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/construction.png",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/modern_template.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/square.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/gloss.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/standard.jpg",
      "//static.gotprint.com/tl/en_US/products/business-cards/info/img/desktop/popular.png",
    ],
  },
  {
    id: 10,
    name: "PromoLine",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMha4iBfMF-P54i0rxc5aSqqWuktU3_Ed0vA&s",
    images: [
      "https://example.com/assets/img/products/promo1.jpg",
      "https://example.com/assets/img/products/promo2.jpg",
      "https://example.com/assets/img/products/promo3.jpg",
      "https://example.com/assets/img/products/promo4.jpg",
      "https://example.com/assets/img/products/promo5.jpg",
      "https://example.com/assets/img/products/promo6.jpg",
      "https://example.com/assets/img/products/promo7.jpg",
      "https://example.com/assets/img/products/promo8.jpg",
      "https://example.com/assets/img/products/promo9.jpg",
      "https://example.com/assets/img/products/promo10.jpg",
      "https://example.com/assets/img/products/promo11.jpg",
      "https://example.com/assets/img/products/promo12.jpg",
      "https://example.com/assets/img/products/promo13.jpg",
      "https://example.com/assets/img/products/promo14.jpg",
      "https://example.com/assets/img/products/promo15.jpg",
      "https://example.com/assets/img/products/promo16.jpg",
    ],
  },
];
